package com.mindx360.mcp.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * JPA entity representing an Employee record stored in the H2 in-memory
 * database.
 *
 * <p>All fields are mapped directly to the EMPLOYEES table. The schema is
 * auto-generated by Hibernate (spring.jpa.hibernate.ddl-auto=create-drop) and
 * seeded by resources/data.sql.
 */
@Entity
@Table(name = "employees")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class Employee {

    /** Primary key – auto-incremented by the H2 sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the employee. */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /** Business unit the employee belongs to (e.g. "IT", "HR", "Finance"). */
    @Column(name = "department", nullable = false, length = 100)
    private String department;

    /** Annual gross salary in USD. */
    @Column(name = "salary", nullable = false)
    private Double salary;

    /** The calendar date the employee joined the company. */
    @Column(name = "joining_date", nullable = false)
    private LocalDate joiningDate;

    /**
     * Current employment status – ACTIVE or INACTIVE.
     * Stored as a VARCHAR so values are human-readable in the H2 console.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private EmployeeStatus status;

    /**
     * The most recent date on which the employee was active (e.g. last login,
     * last work day, or the date their status was set to ACTIVE).
     * Used for time-scoped queries such as "active employees this month".
     */
    @Column(name = "last_active_date")
    private LocalDate lastActiveDate;
}
